/**
	Made by Edoardo Mantovani, 2025
	Simple utility which permits to convert every command into its real 'ID' inside the fw.

**/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <linux/const.h>
#include <asm-generic/bitsperlong.h>

#define ARRAY_SIZE(array)			sizeof(array) / sizeof(array[0])

#define __bf_shf(mask)				(__builtin_ffsll(mask) - 1)
#define UL(VAL)					(_UL(VAL))
#define BIT(NR)					(UL(1) << (NR))
#define __GENMASK(x, y)				(((~_UL(0)) - (_UL(1) << (y)) + 1) & (~UL(0) >> (__BITS_PER_LONG - 1 - (x))))
#define GENMASK(x, y)				__GENMASK(x, y)
#define FIELD_PREP(_mask, _val)			((typeof(_mask))(_val) << __bf_shf(_mask)) & (_mask)

#define __MCU_CMD_FIELD_ID                      GENMASK(7, 0)
#define __MCU_CMD_FIELD_EXT_ID                  GENMASK(15, 8)
#define __MCU_CMD_FIELD_QUERY                   BIT(16)
#define __MCU_CMD_FIELD_UNI                     BIT(17)
#define __MCU_CMD_FIELD_CE                      BIT(18)
#define __MCU_CMD_FIELD_WA                      BIT(19)
#define __MCU_CMD_FIELD_WM                      BIT(20)


#define MCU_CMD(_t)				FIELD_PREP(__MCU_CMD_FIELD_ID,		\
							   MCU_CMD_##_t)
#define MCU_EXT_CMD(_t)				(MCU_CMD(EXT_CID) | \
						 FIELD_PREP(__MCU_CMD_FIELD_EXT_ID,	\
							    MCU_EXT_CMD_##_t))
#define MCU_EXT_QUERY(_t)			(MCU_EXT_CMD(_t) | __MCU_CMD_FIELD_QUERY)
#define MCU_UNI_CMD(_t)				(__MCU_CMD_FIELD_UNI |			\
						 FIELD_PREP(__MCU_CMD_FIELD_ID,		\
							    MCU_UNI_CMD_##_t))
#define MCU_CE_CMD(_t)				(__MCU_CMD_FIELD_CE |			\
						 FIELD_PREP(__MCU_CMD_FIELD_ID,		\
							   MCU_CE_CMD_##_t))
#define MCU_CE_QUERY(_t)			(MCU_CE_CMD(_t) | __MCU_CMD_FIELD_QUERY)

#define MCU_WA_CMD(_t)				(MCU_CMD(_t) | __MCU_CMD_FIELD_WA)
#define MCU_WA_EXT_CMD(_t)			(MCU_EXT_CMD(_t) | __MCU_CMD_FIELD_WA)
#define MCU_WA_PARAM_CMD(_t)			(MCU_WA_CMD(WA_PARAM) | \
						 FIELD_PREP(__MCU_CMD_FIELD_EXT_ID, \
							    MCU_WA_PARAM_CMD_##_t))

#define MCU_WM_UNI_CMD(_t)			(MCU_UNI_CMD(_t) |		\
						 __MCU_CMD_FIELD_WM)
#define MCU_WM_UNI_CMD_QUERY(_t)		(MCU_UNI_CMD(_t) |		\
						 __MCU_CMD_FIELD_QUERY |	\
						 __MCU_CMD_FIELD_WM)
#define MCU_WA_UNI_CMD(_t)			(MCU_UNI_CMD(_t) |		\
						 __MCU_CMD_FIELD_WA)
#define MCU_WMWA_UNI_CMD(_t)			(MCU_WM_UNI_CMD(_t) |		\
						 __MCU_CMD_FIELD_WA)

enum {
	MCU_EXT_CMD_EFUSE_ACCESS = 0x01,
	MCU_EXT_CMD_RF_REG_ACCESS = 0x02,
	MCU_EXT_CMD_RF_TEST = 0x04,
	MCU_EXT_CMD_PM_STATE_CTRL = 0x07,
	MCU_EXT_CMD_CHANNEL_SWITCH = 0x08,
	MCU_EXT_CMD_SET_TX_POWER_CTRL = 0x11,
	MCU_EXT_CMD_FW_LOG_2_HOST = 0x13,
	MCU_EXT_CMD_TXBF_ACTION = 0x1e,
	MCU_EXT_CMD_EFUSE_BUFFER_MODE = 0x21,
	MCU_EXT_CMD_THERMAL_PROT = 0x23,
	MCU_EXT_CMD_STA_REC_UPDATE = 0x25,
	MCU_EXT_CMD_BSS_INFO_UPDATE = 0x26,
	MCU_EXT_CMD_EDCA_UPDATE = 0x27,
	MCU_EXT_CMD_DEV_INFO_UPDATE = 0x2A,
	MCU_EXT_CMD_THERMAL_CTRL = 0x2c,
	MCU_EXT_CMD_WTBL_UPDATE = 0x32,
	MCU_EXT_CMD_SET_DRR_CTRL = 0x36,
	MCU_EXT_CMD_SET_RDD_CTRL = 0x3a,
	MCU_EXT_CMD_ATE_CTRL = 0x3d,
	MCU_EXT_CMD_PROTECT_CTRL = 0x3e,
	MCU_EXT_CMD_DBDC_CTRL = 0x45,
	MCU_EXT_CMD_MAC_INIT_CTRL = 0x46,
	MCU_EXT_CMD_RX_HDR_TRANS = 0x47,
	MCU_EXT_CMD_MUAR_UPDATE = 0x48,
	MCU_EXT_CMD_BCN_OFFLOAD = 0x49,
	MCU_EXT_CMD_RX_AIRTIME_CTRL = 0x4a,
	MCU_EXT_CMD_SET_RX_PATH = 0x4e,
	MCU_EXT_CMD_EFUSE_FREE_BLOCK = 0x4f,
	MCU_EXT_CMD_TX_POWER_FEATURE_CTRL = 0x58,
	MCU_EXT_CMD_RXDCOC_CAL = 0x59,
	MCU_EXT_CMD_GET_MIB_INFO = 0x5a,
	MCU_EXT_CMD_TXDPD_CAL = 0x60,
	MCU_EXT_CMD_CAL_CACHE = 0x67,
	MCU_EXT_CMD_RED_ENABLE = 0x68,
	MCU_EXT_CMD_SET_RADAR_TH = 0x7c,
	MCU_EXT_CMD_SET_RDD_PATTERN = 0x7d,
	MCU_EXT_CMD_MWDS_SUPPORT = 0x80,
	MCU_EXT_CMD_SET_SER_TRIGGER = 0x81,
	MCU_EXT_CMD_TWT_AGRT_UPDATE = 0x94,
	MCU_EXT_CMD_FW_DBG_CTRL = 0x95,
	MCU_EXT_CMD_OFFCH_SCAN_CTRL = 0x9a,
	MCU_EXT_CMD_SET_RDD_TH = 0x9d,
	MCU_EXT_CMD_MURU_CTRL = 0x9f,
	MCU_EXT_CMD_SET_SPR = 0xa8,
	MCU_EXT_CMD_GROUP_PRE_CAL_INFO = 0xab,
	MCU_EXT_CMD_DPD_PRE_CAL_INFO = 0xac,
	MCU_EXT_CMD_PHY_STAT_INFO = 0xad,
};

enum {
	MCU_UNI_CMD_DEV_INFO_UPDATE = 0x01,
	MCU_UNI_CMD_BSS_INFO_UPDATE = 0x02,
	MCU_UNI_CMD_STA_REC_UPDATE = 0x03,
	MCU_UNI_CMD_EDCA_UPDATE = 0x04,
	MCU_UNI_CMD_SUSPEND = 0x05,
	MCU_UNI_CMD_OFFLOAD = 0x06,
	MCU_UNI_CMD_HIF_CTRL = 0x07,
	MCU_UNI_CMD_BAND_CONFIG = 0x08,
	MCU_UNI_CMD_REPT_MUAR = 0x09,
	MCU_UNI_CMD_WSYS_CONFIG = 0x0b,
	MCU_UNI_CMD_REG_ACCESS = 0x0d,
	MCU_UNI_CMD_CHIP_CONFIG = 0x0e,
	MCU_UNI_CMD_POWER_CTRL = 0x0f,
	MCU_UNI_CMD_RX_HDR_TRANS = 0x12,
	MCU_UNI_CMD_SER = 0x13,
	MCU_UNI_CMD_TWT = 0x14,
	MCU_UNI_CMD_SET_DOMAIN_INFO = 0x15,
	MCU_UNI_CMD_SCAN_REQ = 0x16,
	MCU_UNI_CMD_RDD_CTRL = 0x19,
	MCU_UNI_CMD_GET_MIB_INFO = 0x22,
	MCU_UNI_CMD_GET_STAT_INFO = 0x23,
	MCU_UNI_CMD_SNIFFER = 0x24,
	MCU_UNI_CMD_SR = 0x25,
	MCU_UNI_CMD_ROC = 0x27,
	MCU_UNI_CMD_SET_DBDC_PARMS = 0x28,
	MCU_UNI_CMD_TXPOWER = 0x2b,
	MCU_UNI_CMD_SET_POWER_LIMIT = 0x2c,
	MCU_UNI_CMD_EFUSE_CTRL = 0x2d,
	MCU_UNI_CMD_RA = 0x2f,
	MCU_UNI_CMD_MURU = 0x31,
	MCU_UNI_CMD_BF = 0x33,
	MCU_UNI_CMD_CHANNEL_SWITCH = 0x34,
	MCU_UNI_CMD_THERMAL = 0x35,
	MCU_UNI_CMD_VOW = 0x37,
	MCU_UNI_CMD_FIXED_RATE_TABLE = 0x40,
	MCU_UNI_CMD_RRO = 0x57,
	MCU_UNI_CMD_OFFCH_SCAN_CTRL = 0x58,
	MCU_UNI_CMD_PER_STA_INFO = 0x6d,
	MCU_UNI_CMD_ALL_STA_INFO = 0x6e,
	MCU_UNI_CMD_ASSERT_DUMP = 0x6f,
};

enum {
	MCU_CMD_TARGET_ADDRESS_LEN_REQ = 0x01,
	MCU_CMD_FW_START_REQ = 0x02,
	MCU_CMD_INIT_ACCESS_REG = 0x3,
	MCU_CMD_NIC_POWER_CTRL = 0x4,
	MCU_CMD_PATCH_START_REQ = 0x05,
	MCU_CMD_PATCH_FINISH_REQ = 0x07,
	MCU_CMD_PATCH_SEM_CONTROL = 0x10,
	MCU_CMD_WA_PARAM = 0xc4,
	MCU_CMD_EXT_CID = 0xed,
	MCU_CMD_FW_SCATTER = 0xee,
	MCU_CMD_RESTART_DL_REQ = 0xef,
};

/* offload mcu commands */
enum {
	MCU_CE_CMD_TEST_CTRL = 0x01,
	MCU_CE_CMD_START_HW_SCAN = 0x03,
	MCU_CE_CMD_SET_PS_PROFILE = 0x05,
	MCU_CE_CMD_SET_RX_FILTER = 0x0a,
	MCU_CE_CMD_SET_CHAN_DOMAIN = 0x0f,
	MCU_CE_CMD_SET_BSS_CONNECTED = 0x16,
	MCU_CE_CMD_SET_BSS_ABORT = 0x17,
	MCU_CE_CMD_CANCEL_HW_SCAN = 0x1b,
	MCU_CE_CMD_SET_ROC = 0x1c,
	MCU_CE_CMD_SET_EDCA_PARMS = 0x1d,
	MCU_CE_CMD_SET_P2P_OPPPS = 0x33,
	MCU_CE_CMD_SET_CLC = 0x5c,
	MCU_CE_CMD_SET_RATE_TX_POWER = 0x5d,
	MCU_CE_CMD_SCHED_SCAN_ENABLE = 0x61,
	MCU_CE_CMD_SCHED_SCAN_REQ = 0x62,
	MCU_CE_CMD_GET_NIC_CAPAB = 0x8a,
	MCU_CE_CMD_SET_MU_EDCA_PARMS = 0xb0,
	MCU_CE_CMD_REG_WRITE = 0xc0,
	MCU_CE_CMD_REG_READ = 0xc0,
	MCU_CE_CMD_CHIP_CONFIG = 0xca,
	MCU_CE_CMD_FWLOG_2_HOST = 0xc5,
	MCU_CE_CMD_GET_WTBL = 0xcd,
	MCU_CE_CMD_GET_TXPWR = 0xd0,
};

int main(void){

	unsigned int MCU_EXT_ARRAY[]    = {
		MCU_EXT_CMD(EFUSE_ACCESS),
		MCU_EXT_CMD(RF_REG_ACCESS),
		MCU_EXT_CMD(RF_TEST),
		MCU_EXT_CMD(PM_STATE_CTRL),
		MCU_EXT_CMD(CHANNEL_SWITCH),
		MCU_EXT_CMD(SET_TX_POWER_CTRL),
		MCU_EXT_CMD(FW_LOG_2_HOST),
		MCU_EXT_CMD(TXBF_ACTION),
		MCU_EXT_CMD(EFUSE_BUFFER_MODE),
		MCU_EXT_CMD(THERMAL_PROT),
		MCU_EXT_CMD(STA_REC_UPDATE),
		MCU_EXT_CMD(BSS_INFO_UPDATE),
		MCU_EXT_CMD(EDCA_UPDATE),
		MCU_EXT_CMD(DEV_INFO_UPDATE),
		MCU_EXT_CMD(THERMAL_CTRL),
		MCU_EXT_CMD(WTBL_UPDATE),
		MCU_EXT_CMD(SET_DRR_CTRL),
		MCU_EXT_CMD(SET_RDD_CTRL),
		MCU_EXT_CMD(ATE_CTRL),
		MCU_EXT_CMD(PROTECT_CTRL),
		MCU_EXT_CMD(DBDC_CTRL),
		MCU_EXT_CMD(MAC_INIT_CTRL),
		MCU_EXT_CMD(RX_HDR_TRANS),
		MCU_EXT_CMD(MUAR_UPDATE),
		MCU_EXT_CMD(BCN_OFFLOAD),
		MCU_EXT_CMD(RX_AIRTIME_CTRL),
		MCU_EXT_CMD(SET_RX_PATH),
		MCU_EXT_CMD(EFUSE_FREE_BLOCK),
		MCU_EXT_CMD(TX_POWER_FEATURE_CTRL),
		MCU_EXT_CMD(RXDCOC_CAL),
		MCU_EXT_CMD(GET_MIB_INFO),
		MCU_EXT_CMD(TXDPD_CAL),
		MCU_EXT_CMD(CAL_CACHE),
		MCU_EXT_CMD(RED_ENABLE),
		MCU_EXT_CMD(SET_RADAR_TH),
		MCU_EXT_CMD(SET_RDD_PATTERN),
		MCU_EXT_CMD(MWDS_SUPPORT),
		MCU_EXT_CMD(SET_SER_TRIGGER),
		MCU_EXT_CMD(TWT_AGRT_UPDATE),
		MCU_EXT_CMD(FW_DBG_CTRL),
		MCU_EXT_CMD(OFFCH_SCAN_CTRL),
		MCU_EXT_CMD(SET_RDD_TH),
		MCU_EXT_CMD(MURU_CTRL),
		MCU_EXT_CMD(SET_SPR),
		MCU_EXT_CMD(GROUP_PRE_CAL_INFO),
		MCU_EXT_CMD(DPD_PRE_CAL_INFO),
		MCU_EXT_CMD(PHY_STAT_INFO),
	};

	unsigned int MCU_UNI_ARRAY[]    = {
		MCU_UNI_CMD(DEV_INFO_UPDATE),
		MCU_UNI_CMD(BSS_INFO_UPDATE),
		MCU_UNI_CMD(STA_REC_UPDATE),
		MCU_UNI_CMD(EDCA_UPDATE),
		MCU_UNI_CMD(SUSPEND),
		MCU_UNI_CMD(OFFLOAD),
		MCU_UNI_CMD(HIF_CTRL),
		MCU_UNI_CMD(BAND_CONFIG),
		MCU_UNI_CMD(REPT_MUAR),
		MCU_UNI_CMD(WSYS_CONFIG),
		MCU_UNI_CMD(REG_ACCESS),
		MCU_UNI_CMD(CHIP_CONFIG),
		MCU_UNI_CMD(POWER_CTRL),
		MCU_UNI_CMD(RX_HDR_TRANS),
		MCU_UNI_CMD(SER),
		MCU_UNI_CMD(TWT),
		MCU_UNI_CMD(SET_DOMAIN_INFO),
		MCU_UNI_CMD(SCAN_REQ),
		MCU_UNI_CMD(RDD_CTRL),
		MCU_UNI_CMD(GET_MIB_INFO),
		MCU_UNI_CMD(GET_STAT_INFO),
		MCU_UNI_CMD(SNIFFER),
		MCU_UNI_CMD(SR),
		MCU_UNI_CMD(ROC),
		MCU_UNI_CMD(SET_DBDC_PARMS),
		MCU_UNI_CMD(TXPOWER),
		MCU_UNI_CMD(SET_POWER_LIMIT),
		MCU_UNI_CMD(EFUSE_CTRL),
		MCU_UNI_CMD(RA),
		MCU_UNI_CMD(MURU),
		MCU_UNI_CMD(BF),
		MCU_UNI_CMD(CHANNEL_SWITCH),
		MCU_UNI_CMD(THERMAL),
		MCU_UNI_CMD(VOW),
		MCU_UNI_CMD(FIXED_RATE_TABLE),
		MCU_UNI_CMD(RRO),
		MCU_UNI_CMD(OFFCH_SCAN_CTRL),
		MCU_UNI_CMD(PER_STA_INFO),
		MCU_UNI_CMD(ALL_STA_INFO),
		MCU_UNI_CMD(ASSERT_DUMP),
	};

	unsigned int MCU_CMD_ARRAY[]    = {
		MCU_CMD(TARGET_ADDRESS_LEN_REQ),
		MCU_CMD(FW_START_REQ),
		MCU_CMD(INIT_ACCESS_REG),
		MCU_CMD(NIC_POWER_CTRL),
		MCU_CMD(PATCH_START_REQ),
		MCU_CMD(PATCH_FINISH_REQ),
		MCU_CMD(PATCH_SEM_CONTROL),
		MCU_CMD(WA_PARAM),
		MCU_CMD(EXT_CID),
		MCU_CMD(FW_SCATTER),
		MCU_CMD(RESTART_DL_REQ),
	};

	unsigned int MCU_CE_ARRAY[] = {
		MCU_CE_CMD(TEST_CTRL),
		MCU_CE_CMD(START_HW_SCAN),
		MCU_CE_CMD(SET_PS_PROFILE),
		MCU_CE_CMD(SET_RX_FILTER),
		MCU_CE_CMD(SET_CHAN_DOMAIN),
		MCU_CE_CMD(SET_BSS_CONNECTED),
		MCU_CE_CMD(SET_BSS_ABORT),
		MCU_CE_CMD(CANCEL_HW_SCAN),
		MCU_CE_CMD(SET_ROC),
		MCU_CE_CMD(SET_EDCA_PARMS),
		MCU_CE_CMD(SET_P2P_OPPPS),
		MCU_CE_CMD(SET_CLC),
		MCU_CE_CMD(SET_RATE_TX_POWER),
		MCU_CE_CMD(SCHED_SCAN_ENABLE),
		MCU_CE_CMD(SCHED_SCAN_REQ),
		MCU_CE_CMD(GET_NIC_CAPAB),
		MCU_CE_CMD(SET_MU_EDCA_PARMS),
		MCU_CE_CMD(REG_WRITE),
		MCU_CE_CMD(REG_READ),
		MCU_CE_CMD(CHIP_CONFIG),
		MCU_CE_CMD(FWLOG_2_HOST),
		MCU_CE_CMD(GET_WTBL),
		MCU_CE_CMD(GET_TXPWR),
	};

	printf("MCU_EXT_ARRAY commands:\n");
	for(unsigned int j = 0; j < ARRAY_SIZE(MCU_EXT_ARRAY); j++){
		printf("0x%x\n", MCU_EXT_ARRAY[j]);

	}

        printf("MCU_UNI_ARRAY commands:\n");
        for(unsigned int j = 0; j < ARRAY_SIZE(MCU_UNI_ARRAY); j++){
                printf("0x%x\n", MCU_UNI_ARRAY[j]);

        }

        printf("MCU_CE_ARRAY commands:\n");
        for(unsigned int j = 0; j < ARRAY_SIZE(MCU_CE_ARRAY); j++){
                printf("0x%x\n", MCU_CE_ARRAY[j]);

        }
	return 0;
}
